version: '3'
services:
  gpt-researcher:
    build: ./
    environment: 
      OPENAI_API_KEY:  
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /usr/src/app