version: '3'
services:
  gpt-researcher:
    build: ./
    environment: 
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY} 
      SMART_LLM_MODEL: ${SMART_LLM_MODEL}
      PYTHONUNBUFFERED: 1
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /usr/src/app